services:
  gcloud:
    image: google/cloud-sdk:latest
    platform: linux/amd64
    volumes:
      - 'gcp:/root/.config/'
    entrypoint: gcloud

  dev: &dev
    image: gfw/pipe-gaps-dev
    platform: linux/amd64
    build:
      target: dev
    volumes:
      - '.:/opt/project'
      - 'gcp:/root/.config/'
    entrypoint: /bin/bash

  dev_no_gcp:
    image: gfw/pipe-gaps-dev
    # Dev container without GCP credentials.
    <<: *dev
    volumes:
      - ".:/opt/project"

  prod:
    image: gfw/pipe-gaps-prod
    build:
      target: prod
    platform: linux/amd64
    entrypoint: /bin/bash

  test:
    image: gfw/pipe-gaps-test
    platform: linux/amd64
    # Runs tests using the production Docker image.
    # Intended to be executed in the GitHub CI environment.
    build:
      target: test
    entrypoint: 'pytest -v'

volumes:
  gcp:
    external: true
