bq_in_messages: gfw-int-pipe-v3.pipe_ais_v3_internal.research_messages
bq_in_segments: global-fishing-watch.pipe_ais_v3_published.segs_activity
bq_out_gaps: world-fishing-827.scratch_tomas_ttl30d.raw_gaps_pipeline_4615_2026_7days
bq_in_open_gaps: gfw-int-pipe-v3.pipe_ais_v3_internal.raw_gaps
open_gaps_start_date: "2020-02-01"
skip_open_gaps: false
date_range: ["2026-09-01", "2026-09-08"]
min_gap_length: 6
n_hours_before: 12
window_period_d: 1
filter_good_seg: true

# Apache Beam options
runner: dataflow
project: world-fishing-827
max_num_workers: 200
machine_type: e2-custom-2-3072
job_name: tom-test-gaps-pipeline-4615-2026-7days
temp_location: gs://gfw-dataflow-temp-staging-ttl-7/dataflow_temp
staging_location: gs://gfw-dataflow-temp-staging-ttl-7/dataflow_staging
region: us-central1
subnetwork: regions/us-central1/subnetworks/gfw-internal-us-central1
service_account_email: engineering-development@world-fishing-827.iam.gserviceaccount.com
