bq_input_messages: gfw-int-vms-v3.pipe_vms_v3_internal.research_messages
bq_input_segments: global-fishing-watch.pipe_vms_v4_published.segs_activity
bq_output_gaps: world-fishing-827.scratch_tomas_ttl30d.raw_gaps_vms_backfill
date_range:
  - "2012-01-01"
  - "2026-05-07"
open_gaps_start_date: "2012-01-01"
filter_good_seg: true
min_gap_length: 1
n_hours_before: 12
window_period_d: 180
no_rich_logging: true
good_seg_stabilization_days: 0

# Apache Beam options
project: world-fishing-827
runner: dataflow
max_num_workers: 300
machine_type: e2-highmem-2
temp_location: gs://pipe-temp-us-central-ttl7/dataflow_temp
staging_location: gs://pipe-temp-us-central-ttl7/dataflow_staging
region: us-central1
subnetwork: regions/us-central1/subnetworks/gfw-internal-us-central1
# sdk_container_image: us-central1-docker.pkg.dev/gfw-int-infrastructure/core/pipe-gaps:v0.9.5
service_account_email: pipeline-vms-v3@gfw-int-vms-v3.iam.gserviceaccount.com
job_name: detect-gaps-vms-backfill--2012-01-01--2026-05-08